name = "marketplace-gdg-store"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

# Hyperdrive configuration
[[hyperdrive]]
binding = "HYPERDRIVE_DB"
id = "89f4454b0426402397a1b857e251495f"
localConnectionString = "postgresql://neondb_owner:npg_wS8ux1paQcqY@ep-dawn-field-acydf752-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"

# Environment variables
[vars]
NODE_ENV = "production"

# KV Namespaces para cache
[[kv_namespaces]]
binding = "CACHE_KV"
id = "780e9e83f99b45f4a6ac7a44f6ee8f4b"
preview_id = "f7678a2cec1d438a9bb518f1c820d114"

# D1 Database (se você quiser usar no futuro)
# [[d1_databases]]
# binding = "DB"
# database_name = "marketplace-db"
# database_id = "YOUR_D1_DATABASE_ID"

# Variáveis de ambiente (exemplo)
# PUBLIC_API_URL = "https://api.marketplace-gdg.com"

# Rotas customizadas (se necessário)
# [[routes]]
# pattern = "/api/*"
# zone_name = "marketplace-gdg.com" 