name = "marketplace-gdg-store"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

# Configuração de CPU time estendido para TCP direto
[limits]
cpu_ms = 120000

# Environment variables
[vars]
NODE_ENV = "production"
DATABASE_URL = "postgresql://neondb_owner:npg_wS8ux1paQcqY@ep-dawn-field-acydf752-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"

# KV Namespaces para cache
[[kv_namespaces]]
binding = "CACHE_KV"
id = "780e9e83f99b45f4a6ac7a44f6ee8f4b"
preview_id = "f7678a2cec1d438a9bb518f1c820d114"

# Hyperdrive para otimizar conexões com Neon
[[hyperdrive]]
binding = "HYPERDRIVE_DB"
id = "YOUR_HYPERDRIVE_ID_HERE"
localConnectionString = "postgresql://neondb_owner:npg_wS8ux1paQcqY@ep-dawn-field-acydf752-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require"

# D1 Database (se você quiser usar no futuro)
# [[d1_databases]]
# binding = "DB"
# database_name = "marketplace-db"
# database_id = "YOUR_D1_DATABASE_ID"

# Variáveis de ambiente (exemplo)
# PUBLIC_API_URL = "https://api.marketplace-gdg.com"

# Rotas customizadas (se necessário)
# [[routes]]
# pattern = "/api/*"
# zone_name = "marketplace-gdg.com" 