name = "mktplace-gdg-store"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"

# Variáveis de ambiente serão configuradas no dashboard do Cloudflare
# [vars]
# XATA_API_KEY = "your-api-key"
# XATA_BRANCH = "main"

[vars]
# Adicione suas variáveis de ambiente aqui 