name = "mktplace-store"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = ["nodejs_compat"]

# Hyperdrive configuration
[[hyperdrive]]
binding = "HYPERDRIVE_DB"
id = "14a8dd340a754f9c9afd52c5c81fd3d3"

# Environment variables
[vars]
NODE_ENV = "production" 