name = "mktplace-store"
compatibility_date = "2024-01-01"
pages_build_output_dir = "apps/store/.svelte-kit/cloudflare"

# Build configuration
[build]
command = "pnpm install && pnpm build:store"

# Environment variables
[vars]
# As variáveis serão configuradas no dashboard do Cloudflare 