-- PARTE 1: Renomear tabelas existentes
-- Execute cada comando individualmente no Xata SQL Editor

ALTER TABLE products RENAME TO products_old;
ALTER TABLE categories RENAME TO categories_old;
ALTER TABLE brands RENAME TO brands_old;
ALTER TABLE product_images RENAME TO product_images_old;
ALTER TABLE sellers RENAME TO sellers_old;
ALTER TABLE users RENAME TO users_old;
ALTER TABLE addresses RENAME TO addresses_old;
ALTER TABLE orders RENAME TO orders_old;
ALTER TABLE order_items RENAME TO order_items_old;
ALTER TABLE cart_items RENAME TO cart_items_old;
ALTER TABLE abandoned_carts RENAME TO abandoned_carts_old;
ALTER TABLE wishlists RENAME TO wishlists_old;
ALTER TABLE product_reviews RENAME TO product_reviews_old;
ALTER TABLE product_variants RENAME TO product_variants_old;
ALTER TABLE product_options RENAME TO product_options_old;
ALTER TABLE product_option_values RENAME TO product_option_values_old;
ALTER TABLE variant_option_values RENAME TO variant_option_values_old;
ALTER TABLE coupons RENAME TO coupons_old;
ALTER TABLE coupon_usage RENAME TO coupon_usage_old;
ALTER TABLE payment_methods RENAME TO payment_methods_old;
ALTER TABLE payment_transactions RENAME TO payment_transactions_old;
ALTER TABLE shipping_methods RENAME TO shipping_methods_old;
ALTER TABLE shipping_zones RENAME TO shipping_zones_old;
ALTER TABLE notifications RENAME TO notifications_old;
ALTER TABLE notification_preferences RENAME TO notification_preferences_old;
ALTER TABLE user_sessions RENAME TO user_sessions_old;
ALTER TABLE product_analytics RENAME TO product_analytics_old;
ALTER TABLE product_price_history RENAME TO product_price_history_old;
ALTER TABLE system_settings RENAME TO system_settings_old; 