-- PARTE 2C: Criar tabelas de produtos

-- Tabela Products (depende de brands, categories, sellers)
CREATE TABLE products (
    xata_id TEXT PRIMARY KEY DEFAULT ('rec_' || replace(gen_random_uuid()::text, '-', '')),
    id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    sku TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    brand_id UUID REFERENCES brands(id),
    category_id UUID REFERENCES categories(id),
    seller_id UUID REFERENCES sellers(id),
    status TEXT NOT NULL DEFAULT 'active',
    is_active BOOLEAN NOT NULL DEFAULT true,
    price DECIMAL(10,2) NOT NULL,
    original_price DECIMAL(10,2),
    cost DECIMAL(10,2),
    currency TEXT NOT NULL DEFAULT 'BRL',
    quantity INTEGER NOT NULL DEFAULT 0,
    stock_location TEXT,
    track_inventory BOOLEAN NOT NULL DEFAULT true,
    allow_backorder BOOLEAN NOT NULL DEFAULT false,
    weight DECIMAL(10,3),
    height DECIMAL(10,2),
    width DECIMAL(10,2),
    length DECIMAL(10,2),
    meta_title TEXT,
    meta_description TEXT,
    meta_keywords TEXT[],
    tags TEXT[],
    attributes JSONB DEFAULT '{}'::jsonb,
    specifications JSONB DEFAULT '{}'::jsonb,
    view_count INTEGER NOT NULL DEFAULT 0,
    sales_count INTEGER NOT NULL DEFAULT 0,
    rating_average DECIMAL(3,2),
    rating_count INTEGER NOT NULL DEFAULT 0,
    featured BOOLEAN DEFAULT false,
    barcode TEXT,
    featuring JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    published_at TIMESTAMPTZ,
    xata_version INTEGER NOT NULL DEFAULT 0,
    xata_createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    xata_updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    xata JSONB DEFAULT '{"version":0}'::jsonb
);

-- Tabela Product Images (depende de products)
CREATE TABLE product_images (
    xata_id TEXT PRIMARY KEY DEFAULT ('rec_' || replace(gen_random_uuid()::text, '-', '')),
    id UUID UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_primary BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    xata_version INTEGER NOT NULL DEFAULT 0,
    xata_createdat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    xata_updatedat TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    xata JSONB DEFAULT '{"version":0}'::jsonb
); 