name = "mktplace-admin"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "workers-site/index.js"

[site]
bucket = ".svelte-kit/cloudflare"

[build]
command = "pnpm run build"

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt", "**/*.html"] 